name: SAST (Dev)
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  native_scanner:
    name: Boost Native Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download snyk
        run: |
          curl https://static.snyk.io/cli/latest/snyk-linux -o /tmp/snyk
          chmod +x /tmp/snyk
          /tmp/snyk auth ${{ secrets.SNYK_TOKEN }}

          docker pull public.ecr.aws/boostsecurityio/boostsecurityio-convert-snyk:latest

          cat <<EOF > /tmp/snyk-wrapper
          #!/bin/bash
          /tmp/snyk test --json |
          docker run \
            --rm \
            --interactive \
            public.ecr.aws/boostsecurityio/boostsecurityio-convert-snyk:latest \
            process -
          EOF
          chmod +x /tmp/snyk-wrapper
      - name: BoostSecurity Scanner
        uses: boostsecurityio/boostsec-scanner-github@v3
        with:
          action: scan
          api_endpoint: https://api.dev.boostsec.io
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
      - name: Snyk Scanner
        uses: boostsecurityio/boostsec-scanner-github@v3
        with:
          action: exec
          api_endpoint: https://api.dev.boostsec.io
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
          exec_command: /tmp/snyk-wrapper
          additional_args: --require-full-repo
          step_name: snyk-sca
